name: Release Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  # Build for macOs
  release_macos:
    name: macOS cppandaction+diatonic lib release
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      run: cmake -S . -B build -DGIT_ACTION=TRUE -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ./build --config Release

    - name: Create Artifact
      run: |
        mkdir release
        # cp build/examples release/examples
        cp -r build/externals release/externals
    
    - name: Publish macOS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: intervals macOS release
        path: release
